---
- name: Exercise for setting up a web server in an EC 
  hosts: all
  # Use the public IP if the VM is already created
  # hosts: 54.89.42.83
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
   - setup